// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Simulate
#pragma kernel Generate

#include "Noise.cginc"

#define PI 3.14159265359

uint2 dim;
float cellSize;
float doubleCellSize;

Texture2D<float4> input;
RWTexture2D<float4> result;

// Simulation Parameters:
float u;   // uplift
float c;   // creep speed
float r;   // amount of rain per pixel
float e0;  // bedrock erosion speed
float e1;  // regolith erosion speed
float m;   // water erosion exponent (water depth multiplier)
float n;   // water erosion exponent (slope multiplier)
float s;   // sedimentation rate
float w;   // weathering rate
float p0;  // regolith protection exponent (protecting against bedrock erosion)
float p1;  // regolith protection exponent (protecting against bedrock weathering)
float dt;  // timestep


float4 sample5(uint2 coord, Texture2D<float4> tex, out float4 px, out float4 nx, out float4 py, out float4 ny)
{
    // Get neighbours and wrap correctly around (Edge vertices are duplicated, and so need to go 1 further when wrapping)
    if (coord.x + 1 == dim.x) px = tex[uint2(1, coord.y)];
    else                      px = tex[uint2(coord.x + 1, coord.y)];
    if (coord.x == 0)         nx = tex[uint2(dim.x - 2, coord.y)];
    else                      nx = tex[uint2(coord.x - 1, coord.y)];
    if (coord.y + 1 == dim.y) py = tex[uint2(coord.x, 1)];
    else                      py = tex[uint2(coord.x, coord.y + 1)];
    if (coord.y == 0)         ny = tex[uint2(coord.x, dim.y - 2)];
    else                      ny = tex[uint2(coord.x, coord.y - 1)];
    
    return tex[coord];
}


[numthreads(8, 8, 1)]
void Simulate (uint3 id : SV_DispatchThreadID)
{
    uint2 coord = id.xy;
    
    float4 px;
    float4 nx;
    float4 py;
    float4 ny;
    float4 here = sample5(coord, input, px, nx, py, ny);
    
    float landHeightLaplacian = dot(1.f.xx, (px.xy + nx.xy + py.xy + ny.xy - 4 * here.xy)) / cellSize;
    
    float diffPx = dot(1.f.xxx, px.xyz - here.xyz);
    float diffNx = dot(1.f.xxx, nx.xyz - here.xyz);
    float diffPy = dot(1.f.xxx, py.xyz - here.xyz);
    float diffNy = dot(1.f.xxx, ny.xyz - here.xyz);
    
    float waterFlow = (diffPx * (diffPx > 0 ? px.z : here.z) + // Positive -> flow in | Negative -> flow out
                       diffNx * (diffNx > 0 ? nx.z : here.z) +
                       diffPy * (diffPy > 0 ? py.z : here.z) +
                       diffNy * (diffNy > 0 ? ny.z : here.z)) / cellSize;
    float sedimentFlow = (diffPx * (diffPx > 0 ? px.w : here.w) + // Positive -> flow in | Negative -> flow out
                          diffNx * (diffNx > 0 ? nx.w : here.w) +
                          diffPy * (diffPy > 0 ? py.w : here.w) +
                          diffNy * (diffNy > 0 ? ny.w : here.w)) / cellSize;
    
    float waterSurfaceSlope = length(float2(diffPx - diffNx, diffPy - diffNy) / doubleCellSize); // Average gradient across point
    float streamPower = here.z > 0 && waterSurfaceSlope > 0 ? pow(here.z, m) * pow(waterSurfaceSlope, n) : 0; // Compiler can handle fixed pow(0,y) but shader can't handle dynamic pow(x,y) where x = 0
    
    float bedrockErosion = e0 * streamPower * exp(-here.y * p0);
    float bedrockWeathering = w * exp(-here.y * p1);
    
    float regolithErosion = min(e1 * streamPower, here.y); // Can't erode more regolith than exists at this location
    float regolithCreep = c * landHeightLaplacian;
    
    float sedimentation = here.z > 0 ? s * here.w / here.z : here.w;
    
    float dw = r + waterFlow; // Change in water depth with respect to time
    float dh = -bedrockErosion - bedrockWeathering + u; // Change in bedrock height with respect to time
    float dp = regolithCreep - regolithErosion + bedrockWeathering + sedimentation; // Change in regolith thickness with respect to time
    float dl = sedimentFlow + bedrockErosion + regolithErosion - sedimentation; // Change in transported sediment with respect to time

    float4 newState = here + dt * float4(dh, dp, dw, dl);
    
    result[coord] = float4(newState.x, max(0, newState.y), max(0, newState.z), max(0, newState.w)); // this max should never actually do anything unless something goes wrong
}


uint octaves;
float noiseScale;

RWTexture2D<float4> genResult;
float width;
float height;
float left;
float bottom;
float4 seed;

[numthreads(8, 8, 1)]
void Generate(uint3 id : SV_DispatchThreadID)
{
    float s = id.x / float(dim.x - 1);
    float t = id.y / float(dim.y - 1);
    
    float nx = seed[0] + left + cos(s * 2 * PI) * width / (2 * PI);
    float ny = seed[1] + bottom + cos(t * 2 * PI) * height / (2 * PI);
    float nz = seed[2] + left + sin(s * 2 * PI) * width / (2 * PI);
    float nw = seed[3] + bottom + sin(t * 2 * PI) * height / (2 * PI);
    
    float frequency = 1 / noiseScale;
    float scale = 10;
    
    float sum = 0;
    for (uint i = 0; i < octaves; i++)
    {
        sum += snoise(float4(nx, ny, nz, nw) * frequency) * scale;
        scale *= 0.5;
        frequency *= 2;
    }
    
    genResult[id.xy] = float4(sum, 0.1, max(0, -sum - 0.1), 0);
}