// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Tex

uint2 dim;

bool elevationLines = true;

int bedrockThresholds;
int waterThresholds;
StructuredBuffer<float> thresholds;
StructuredBuffer<float4> colours;

Texture3D<float> stateTexture;
RWTexture2D<float4> visTexture;

float4 stack(float4 below, float4 above)
{
    if(below.a == 0 || above.a == 1) return above;
    if(above.a == 0) return below;
    
    return float4(above.rgb * above.a + below.rgb * (1 - above.a), above.a + (1 - above.a) * below.a);
}

float4 sampleThreshold(int first, int last, float value)
{
    if (!(value < 0.f || value > 0.f || value == 0.f)) return float4(1, 0, 1, 1); // Value is NaN -> Pink
    else if (isinf(value)) return float4(1, 0, 0, 1); // Value is infinite -> Red
    
    float curr = thresholds[first];
    if (value <= curr) return colours[first];
    else
    {
        for (int i = first; i < last; i++)
        {
            float next = thresholds[i + 1];
            if (curr < value && value <= next)
            {
                return lerp(colours[i], colours[i + 1], (value - curr) / (next - curr));
            }
            curr = next;
        }
    }
    return colours[last];
}

[numthreads(8, 8, 1)]
void Tex(uint3 id : SV_DispatchThreadID)
{
    float2 states = float2(stateTexture[uint3(id.xy, 0)], stateTexture[uint3(id.xy, 1)]);
    float4 colour = float4(1, 1, 0, 0); // No valid thresholds -> Yellow
    int first = 0;
    colour = sampleThreshold(first, first + bedrockThresholds - 1, states.x); // Bedrock
    float distance = fmod(abs(states.x), 250);
    if(elevationLines && (distance <= 2.5 || distance >= 247.5)) colour = float4(1,1,0.6,1);
    first += bedrockThresholds;
    colour = stack(colour, sampleThreshold(first, first + waterThresholds - 1, states.y)); // Water
    
    //float pressure = min(1, 287.052874 * stateTexture[uint3(id.xy, 5)] * stateTexture[uint3(id.xy, 3)] / (6000 * 25 * 25));
    //colour = float4(min(1, stateTexture[uint3(id.xy, 3)] / 125000000), min(1, stateTexture[uint3(id.xy, 5)] / 288.15), pressure, 1);
    
    colour.a = 1;
    
    visTexture[id.xy] = colour;
}

