// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Tex

uint2 dim;

int numThresholds[3];
StructuredBuffer<float> thresholds;
StructuredBuffer<float4> colours;

Texture2D<float4> stateTexture;
RWTexture2D<float4> visTexture;

float4 stack(float4 below, float4 above)
{
    if(below.a == 0) return above;
    if(above.a == 0) return below;
    
    return float4(above.rgb * above.a + below.rgb * (1 - above.a), above.a + (1 - above.a) * below.a);
}

[numthreads(8, 8, 1)]
void Tex(uint3 id : SV_DispatchThreadID)
{
    float4 states = stateTexture[id.xy];
    float4 colour = float4(0, 0, 0, 0);
    int first = 0;
    for(int t = 0; t < 3; t++)
    {
        if (numThresholds[t] > 0)
        {
            float value = (t == 0) ? states.x : (t == 1) ? states.y : states.z;
            if (!(value < 0.f || value > 0.f || value == 0.f)) colour = float4(1, 0, 1, 1); // Value is NaN -> Pink
            else if (isinf(value)) colour = float4(1, 0, 0, 1); // Value is infinite -> Red
            
            float curr = thresholds[first];
            if (value < curr) colour = colours[first];
            else if (value > thresholds[first + numThresholds[t] - 1]) colour = colours[first + numThresholds[t] - 1];
            else
            {
                for (int i = first; i - first < numThresholds[t] - 1; i++)
                {
                    float next = thresholds[i + 1];
                    if (curr < value && value < next)
                    {
                        colour = stack(colour, lerp(colours[i], colours[i + 1], (value - curr) / (next - curr)));
                        break;
                    }
                    curr = next;
                }
            }
            first += numThresholds[t];
        }
    }
    
    colour.a = 1;
    
    visTexture[id.xy] = colour;
}

